version: 2

linters:
  enable:
    - gocyclo
    - godot
    - predeclared
    - unconvert

formatters:
  enable:
    - gofumpt

linter-settings:
  go-cyclo:
    min-complexity: 15
  godot:
    scope: all
    capital: true
